# Generated by Django 5.2 on 2025-10-11 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrollment_no",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "college",
                    models.CharField(default="BPUT Affiliated College", max_length=200),
                ),
                (
                    "branch",
                    models.CharField(default="Computer Science", max_length=100),
                ),
                ("semester", models.IntegerField(default=1)),
                ("cgpa", models.FloatField(default=0.0)),
                (
                    "skills",
                    models.TextField(
                        default="Python, Java", help_text="Comma separated skills"
                    ),
                ),
                (
                    "interests",
                    models.TextField(
                        default="Web Development, AI",
                        help_text="Comma separated interests",
                    ),
                ),
                ("projects", models.TextField(blank=True)),
                ("certifications", models.TextField(blank=True)),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resumes/"),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
