# Generated by Django 5.2 on 2025-10-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="certifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="interests",
            field=models.TextField(default="Web Development, AI, Data Science"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="projects",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="skills",
            field=models.TextField(default="Python, Java, SQL, Communication"),
        ),
    ]
