# Generated by Django 5.2 on 2025-10-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_studentprofile_updated_at_and_more"),
    ]

    operations = []
