# Generated by Django 5.2 on 2025-10-15 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_update_existing_profiles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="github_url",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="linkedin_url",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="profile_picture",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="interests",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="skills",
            field=models.TextField(default="Python, Communication"),
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("industry", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("required_skills", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("salary", models.CharField(blank=True, max_length=100)),
                ("application_deadline", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.companyprofile",
                    ),
                ),
            ],
        ),
    ]
