# Generated by Django 5.2 on 2025-10-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_studentprofile_certifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="certifications",
            field=models.TextField(
                blank=True, default="", help_text="List your certifications and courses"
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="projects",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Describe your projects and work experience",
            ),
        ),
    ]
