# Generated by Django 5.2 on 2025-10-23 07:44

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_post_comment_userprofile_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Upload documents (PDF, DOCX, PPT, Excel, etc.) - Max 1GB",
                max_length=255,
                null=True,
                upload_to="posts/documents/",
                validators=[
                    users.validators.validate_file_size,
                    users.validators.validate_file_extension,
                ],
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("document", "Document"),
                    ("none", "None"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload images (JPG, PNG, GIF, etc.) - Max 1GB",
                null=True,
                upload_to="posts/images/",
                validators=[
                    users.validators.validate_file_size,
                    users.validators.validate_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("student", "Student Post"),
                    ("company", "Company Post"),
                    ("university", "University Post"),
                    ("opportunity", "Opportunity Post"),
                    ("achievement", "Achievement Post"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload videos (MP4, MOV, AVI, etc.) - Max 1GB",
                max_length=255,
                null=True,
                upload_to="posts/videos/",
                validators=[
                    users.validators.validate_file_size,
                    users.validators.validate_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="branch",
            field=models.CharField(
                choices=[
                    ("Computer Science", "Computer Science"),
                    ("Electrical Engineering", "Electrical Engineering"),
                    ("Civil Engineering", "Civil Engineering"),
                    ("Mechanical Engineering", "Mechanical Engineering"),
                    ("Electronics Engineering", "Electronics Engineering"),
                    ("Information Technology", "Information Technology"),
                    ("Chemical Engineering", "Chemical Engineering"),
                    ("Biotechnology", "Biotechnology"),
                ],
                default="Computer Science",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="profile_photos/default-avatar.png",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
    ]
