# Generated by Django 5.2 on 2025-10-18 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("company_org", models.CharField(max_length=200)),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("job", "Job"),
                            ("course", "Course"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("internshala", "Internshala"),
                            ("naukri", "Naukri"),
                            ("linkedin", "LinkedIn"),
                            ("coursera", "Coursera"),
                            ("nptel", "NPTEL"),
                            ("geeksforgeeks", "GeeksForGeeks"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("skills_required", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("experience_level", models.CharField(max_length=50)),
                ("salary_info", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("last_verified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_recommendations_viewed", models.IntegerField(default=0)),
                ("opportunities_saved", models.IntegerField(default=0)),
                ("skills_improved", models.IntegerField(default=0)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("recommendation_patterns", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_engine.opportunity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "opportunity")},
            },
        ),
    ]
